experiment:
  dataset: movielens1m
  data_config:
    strategy: dataset
    dataset_path: ../data/{0}/dataset.tsv
    dataloader: KGFlexLoader
    side_information:
      work_directory: ../data/{0}
      map: ../data/{0}/mapping.tsv
      features: ../data/{0}/item_features.tsv
      predicates: ../data/{0}/predicate_mapping.tsv
  prefiltering:
    strategy: iterative_k_core
    core: 10
  splitting:
    test_splitting:
      strategy: random_subsampling
      test_ratio: 0.2
  top_k: 10
  gpu: 1
  external_models_path: ../external/models/__init__.py
  evaluation:
    cutoffs: [10, 9, 8, 7, 6, 5, 4, 3, 2, 1]
    simple_metrics: [nDCGRendle2020, nDCG, HR, Precision, Recall, MAP, MRR, ItemCoverage, UserCoverage, NumRetrieved, UserCoverage, Gini, SEntropy, EFD, EPC, PopREO, PopRSP, ACLT, APLT, ARP]
    relevance_threshold: 3
  models:
    external.LightGCN:
      meta:
        validation_rate: 1
        verbose: True
        save_weights: False
        save_recs: False
        validation_metric: nDCG
        restore: False
      lr: 0.001
      epochs: 1
      factors: 64
      batch_size: 1024
      l_w: 0.0001
      n_layers: 3
