experiment:
  dataset: facebook-books
  data_config:
    strategy: dataset
    dataset_path: ../data/{0}/dataset.tsv
    dataloader: KGFlexLoader
    side_information:
      work_directory: ../data/{0}
      map: ../data/{0}/mapping.tsv
      features: ../data/{0}/item_features.tsv
      predicates: ../data/{0}/predicate_mapping.tsv
  prefiltering:
    strategy: iterative_k_core
    core: 5
  splitting:
    test_splitting:
        strategy: random_subsampling
        test_ratio: 0.2
  top_k: 10
  gpu: 0
  external_models_path: ../external/models/__init__.py
  evaluation:
    cutoffs: [10, 1]
    simple_metrics: [nDCGRendle2020, nDCG, HR, Precision, Recall, MAP, MRR, ItemCoverage, UserCoverage, NumRetrieved,
                     UserCoverage, Gini, SEntropy, EFD, EPC, PopREO, PopRSP, ACLT, APLT, ARP]
  models:
    external.LightGCN:
      meta:
        verbose: True
        validation_rate: 141
        save_recs: True
        save_weights: False
        restore: False
      lr: 0.0003087013410270289
      epochs: 141
      factors: 64
      batch_size: 1024
      l_w: 0.006008395850822256
      n_layers: 3
      seed: 42

